before_commands:
    - git clone --branch 7.x-2.x http://git.drupal.org/project/coder.git /tmp/coder

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: /tmp/coder/coder_sniffer/Drupal
        extensions:
            - php
            - module
            - inc
            - install
            - test
            - profile
            - theme
        filter:
            excluded_paths:
              - tmp/*

    php_mess_detector:
        enabled: true
        extensions:
            - php
            - module
            - inc
            - install
            - test
            - profile
            - theme

    php_cpd:
        enabled: true
        names:
            - '*.php'
            - '*.module'
            - '*.inc'
            - '*.install'
            - '*.test'
            - '*.profile'
            - '*.theme'
